dsc/models.py
import urllib2
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from webu.models import LastPublishedObjectPluginBase, ObjectManager
from tango.models import Content
from django.utils.encoding import python_2_unicode_compatible
from webu.custom_models.registry import custom_model
from cms.plugin_base import CMSPluginBase
from cms.models.pluginmodel import CMSPlugin

AUTH_USER_MODEL = settings.AUTH_USER_MODEL

# Device Server statuses
STATUS_NEW = 'new'
STATUS_VERIFIED = 'verified'
STATUS_UPDATED = 'updated'
STATUS_CERTIFIED= 'certified'
STATUS_ARCHIVED = 'archived'
STATUS_DELETED = 'deleted'
STATUS_CHOICES = (
    (STATUS_NEW, 'New'),
    (STATUS_VERIFIED, 'Verified'),
    (STATUS_UPDATED, 'Updated'),
    (STATUS_CERTIFIED, 'Certified'),
    (STATUS_ARCHIVED, 'Archived'),
    (STATUS_DELETED, 'Deleted'),
)

# Device Server statuses
DEV_STATUS_NEW = 'new'
DEV_STATUS_RELEASED = 'released'
DEV_STATUS_MAINTENANCE = 'maintenance'
DEV_STATUS_BROKEN = 'broken'
DEV_STATUS_CHOICES = (
    (DEV_STATUS_NEW, 'New development'),
    (DEV_STATUS_RELEASED, 'Released'),
    (DEV_STATUS_MAINTENANCE, 'In maintenance'),
    (DEV_STATUS_BROKEN, 'Broken'),
)

# List of Device Servers activities
# TODO fill list, do we add subactivites of edit like import form, add attribute etc
DS_ACTIVITY_ADD = 'add'
DS_ACTIVITY_EDIT = 'edit'
DS_ACTIVITY_DOWNLOAD = 'download'
DS_ACTIVITY_DELETE = 'delete'
DS_ACTIVITY_APPLY_FOR_CERT = 'apply_for_cert'
DS_ACTIVITY_CERTIFY = 'certify'
DS_ACTIVITY_VERIFICATION = 'verify'
DS_ACTIVITY_REVERT = 'revert'
DS_ACTIVITY_CHOICES = (
    (DS_ACTIVITY_ADD, 'Created'),
    (DS_ACTIVITY_EDIT, 'Updated'),
    (DS_ACTIVITY_DOWNLOAD, 'Downloaded'),
    (DS_ACTIVITY_DELETE, 'Deleted'),
    (DS_ACTIVITY_APPLY_FOR_CERT, 'Applied for certification'),
    (DS_ACTIVITY_CERTIFY, 'Certificated'),
    (DS_ACTIVITY_VERIFICATION, 'Verified'),
    (DS_ACTIVITY_VERIFICATION, 'Reverted'),
)


DS_COMMAND_DATATYPES = {
    'BooleanType': 'DevBoolean',
    'FloatType': 'DevFloat',
    'DoubleType': 'DevDouble',
    'IntType': 'DevLong',
    'LongType': 'DevLong64',
    'ShortType': 'DevShort',
    'StringType': 'DevString',
    'UIntType': 'DevULong',
    'ULongType': 'DevULong64',
    'UShortType': 'DevUShort',
    'UCharType': 'DevUChar',
    'CharType': 'DevChar',
    'CharArrayType': 'DevVarCharArray',
    'DoubleArrayType': 'DevVarDoubleArray',
    'DoubleStringArrayType': 'DevVarDoubleStringArray',
    'FloatArrayType': 'DevVarFloatArray',
    'LongArrayType': 'DevVarLong64Array',
    'IntArrayType': 'DevVarLongArray',
    'LongStringArrayType': 'DevVarLongStringArray',
    'ShortArrayType': 'DevVarShortArray',
    'StringArrayType': 'DevVarStringArray',
    'ULongArrayType': 'DevVarULong64Array',
    'UIntArrayType': 'DevVarULongArray',
    'UShortArrayType': 'DevVarUShortArray',
    'VoidType': 'DevVoid',
    'ConstStringType': 'ConstDevString',
    'StateType': 'State'
}


DS_ATTRIBUTE_DATATYPES = {
    'BooleanType': 'DevBoolean',
    'FloatType': 'DevFloat',
    'DoubleType': 'DevDouble',
    'IntType': 'DevLong',
    'LongType': 'DevLong64',
    'ShortType': 'DevShort',
    'StringType': 'DevString',
    'UIntType': 'DevULong',
    'ULongType': 'DevULong64',
    'UShortType': 'DevUShort',
    'UCharType': 'DevUChar',
    'CharType': 'DevChar',
    'EncodedType': 'DevEncoded',
    'StateType': 'DevState'
}

DS_PROPERTIES_DATATYPES = {
    'BooleanType': 'DevBoolean',
    'FloatType': 'DevFloat',
    'DoubleType': 'DevDouble',
    'IntType': 'DevLong',
    'LongType': 'DevLong64',
    'ShortType': 'DevShort',
    'StringType': 'DevString',
    'UIntType': 'DevULong',
    'ULongType': 'DevULong64',
    'UShortType': 'DevUShort',
    'UCharType': 'DevUChar',
    'CharType': 'DevChar',
    'BooleanVectorType': 'Array of DevBoolean',
    'FloatVectorType': 'Array of DevFloat',
    'DoubleVectorType': 'Array of DevDouble',
    'IntVectorType': 'Array of DevLong',
    'LongVectorType': 'Array of DevLong64',
    'ShortVectorType': 'Array of DevShort',
    'StringVectorType': 'Array of DevString',
    'UIntVectorType': 'Array of DevULong',
    'ULongVectorType': 'Array of DevULong64',
    'UShortVectorType': 'Array of DevUShort',
    'UCharVectorType': 'Array of DevUChar',
    'CharVectorType': 'Array of DevChar',

}


class DscManagedModel(models.Model):

    # objects in the database are not deleted but invalidated
    invalidate_activity = models.ForeignKey('DeviceServerActivity',
                                            related_name='invalidated_%(class)s',
                                            default=None, null=True, blank=True)

    # if object is changed it is marked as
    last_update_activity = models.ForeignKey('DeviceServerActivity',
                                             related_name='updated_%(class)s',
                                             default=None, null=True, blank=True)

    create_activity = models.ForeignKey('DeviceServerActivity',
                                        related_name='created_%(class)s',
                                        default=None, null=True, blank=True)

    def is_valid(self):
        if self.invalidate_activity is None:
            return True
        else:
            return False

    def make_invalid(self, activity):
        """ Invalidate the object and return invalidate object"""
        self.invalidate_activity = activity
        return self

    def is_deleted(self):
        return not self.is_valid()

    def is_updated(self):
        if self.last_update_activity is None:
            return False
        else:
            return True

    def last_update_method(self):
        create_object = None
        if self.last_update_activity is not None and hasattr(self.last_update_activity, 'create_object'):
            create_object = self.last_update_activity.create_object
        elif self.create_activity is not None and hasattr(self.create_activity, 'create_object'):
            create_object = self.create_activity.create_object

        if create_object is not None and create_object.all().count() > 0:
            if create_object.first().use_uploaded_xmi_file:
                return 'file'
            elif create_object.first().use_url_xmi_file:
                return 'url'
        return 'manual'

    def updated_by_script(self):
        create_object = None
        if self.last_update_activity is not None and hasattr(self.last_update_activity, 'create_object'):
            create_object = self.last_update_activity.create_object
        elif self.create_activity is not None and hasattr(self.create_activity, 'create_object'):
            create_object = self.create_activity.create_object

        if create_object is not None and create_object.all().count() > 0:
            return create_object.first().script_operation
        return False

    def update_object(self):
        create_object = None
        if self.last_update_activity is not None and hasattr(self.last_update_activity, 'create_object'):
            create_object = self.last_update_activity.create_object
        elif self.create_activity is not None and hasattr(self.create_activity, 'create_object'):
            create_object = self.create_activity.create_object

        if create_object is not None and create_object.all().count() > 0:
            return create_object.first()
        return None

    def create_object(self):
        c_object = None

        if self.create_activity is not None and hasattr(self.create_activity, 'create_object'):
            c_object = self.create_activity.create_object

        if c_object is not None and c_object.all().count() > 0:
            return c_object.first()
        return None

    def delete(self, activity=None, user=None):
        if activity is None:
            activity = DeviceServerActivity(
                activity_type=DS_ACTIVITY_DELETE,
                activity_info='%s has been deleted.' % self.__str__(),
                created_by=user
            )
        activity.device_server = self.device_server
        activity.save()
        self.make_invalid(activity)
        self.save()

    class Meta:
        abstract = True


@python_2_unicode_compatible
class DeviceServer(DscManagedModel):
    """Model for a DeviceServer basic entities."""

    name = models.CharField(
        max_length=128,
        verbose_name='Device Server')

    description = models.TextField(verbose_name='Description')

    created_by = models.ForeignKey(
        AUTH_USER_MODEL,
        editable=False,
        on_delete=models.SET_NULL,  # important to avoid deletion of entries when user is removed from the system
        related_name='created_device_servers',
        blank=True, null=True,)

    created_at = models.DateTimeField(
        editable=False,
        auto_now_add=True)

    license = models.ForeignKey(
        'DeviceServerLicense',
        editable=True,
        on_delete=models.SET_NULL,  # important to avoid deletion of entries when license is removed from the system
        related_name='licensed_device_servers',
        blank=True, null=True,
        verbose_name='License')

    status = models.CharField(
        verbose_name='Information status',
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_NEW,
    )

    development_status = models.CharField(
        verbose_name='Development status',
        max_length=20,
        choices=DEV_STATUS_CHOICES,
        default=DEV_STATUS_NEW,
        blank=True
    )

    certified = models.BooleanField(
        verbose_name='Certified',
        default=False,
        blank=True
    )

    readme = models.FileField(verbose_name='Readme', upload_to='dsc_readmes', null=True, blank=True, max_length=100000)

    picture = models.ImageField(verbose_name="Picture",
                                upload_to='dsc_pictures',
                                null=True,

dsc/templates/dsc/catalogue_frontpage.html
{% load render_table from django_tables2 %}
{% load cms_tags %}
{% load dsc_tags %}

{% url 'deviceserver_add' as add_url %}

<h4>
    There are device classes for the following <i>families:</i>
</h4>
<p style="font-size:110%;">
{% include 'dsc/inc/families_list.html' %}
</p>
{% include 'dsc/inc/deviceserver_fulltextsearch.html' %}
<p style="margin-top:8px;" >
    <span style="font-size:120%;font-weight:bold;">
        Have you written a new device class?
        <a href="{{ add_url }}">Please share it.</a>
    </span>
</p>
<p style="margin-bottom:10pt; margin-top:5pt;" id="ds-table">
    {% if family %}
        Below you will find device classes of <span style="font-weight:bold;">{{family}}</span> family.
    {% else %}
        {% if search %}
            Below you will find device classes for <span style="font-weight:bold;">{{search}}</span> search string.
        {% else %}
            Below you will find a table with all device classes.
            Please click a family name above or use search to narrow the list.
        {% endif %}
    {% endif %}
    You may also use <a href="{% url 'deviceserver_advanced_search' %}">
        <span style="font-weight:bold;font-size:120%;">advanced search</span>
    </a>
    to find a device class you are looking for.</p>
</p>
<p>
{% include 'dsc/inc/deviceserver_list.html' %}
</p>

dsc/templates/dsc/catalogue_frontpage_old.html
{% load render_table from django_tables2 %}
{% load cms_tags %}
{% load dsc_tags %}

{% url 'deviceserver_add' as add_url %}

<h4>
    There are device classes for the following <i>families:</i>
</h4>
<p style="font-size:110%;">
{% include 'dsc/inc/families_list.html' %}
</p>
{% include 'dsc/inc/deviceserver_fulltextsearch.html' %}
<p style="font-size:120%;margin-top:0px;">
    Here you will find device classes available in the community. Device classes provide among others
    connectivity to equipment. So, if you want to connect your hardware to Tango Controls please check this catalogue.
    One or more device classes can be wrapped as a device server to connect one or more devices to your Tango control
    system. Tango imposes no limit on the number of devices or classes in a device server. It depends on the
    implementation of the device class.
</p>
<p>
    <span style="font-size:120%;font-weight:bold;">
        Did you write a new device class?
        <a href="{{ add_url }}">Please share it.</a>
    </span>
</p>
<p style="margin-bottom:10pt; margin-top:5pt;" id="ds-table">
    {% if family %}
        Below you will find device classes of <span style="font-weight:bold;">{{family}}</span> family.
    {% else %}
        {% if search %}
            Below you will find device classes for <span style="font-weight:bold;">{{search}}</span> search string.
        {% else %}
            Below you will find a table with all device classes.
            Please click a family name above or use search to narrow the list.
        {% endif %}
    {% endif %}
    You may also use <a href="{% url 'deviceserver_advanced_search' %}">
        <span style="font-weight:bold;font-size:120%;">advanced search</span>
    </a>
    to find a device class you are looking for.</p>
</p>
<p>
{% include 'dsc/inc/deviceserver_list.html' %}
</p>

dsc/templates/dsc/deviceserver_add.html
{% extends request.is_ajax|yesno:"layout/ajax.html,dsc/layout/normal.html" %}
{% load cms_tags i18n thumbnail webu_utils %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

{% block content_header %}
<h1 style="text-transform: none">New device server</h1>
{% endblock %}
{% block content %}

<h4>Please provide information necessery to catalogue your device class(es).</h4>
<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
    <table>
        <tbody><tr><td colspan="2">
            {{ form.non_field_errors }}
        </td></tr></tbody>
        {% include 'dsc/inc/deviceserver_form_basic_info.html' %}

    </table>
    <table>
        {% include 'dsc/inc/deviceserver_form_additional_families.html' %}
    </table>
    <table>
        {% include 'dsc/inc/deviceserver_form_repository.html' %}

        {% include 'dsc/inc/deviceserver_form_documentation.html' %}
    </table>
    <p>
    <button type="submit" class="save btn btn-default">Create</button>
    <a href="{% page_url request.current_page %}" class="dsc-back">Cancel</a>
    </p>
</form>

{% endblock %}

{% block extra_script %}

    {{ block.super }}

    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

    {{ form.media }}


{% endblock %}

dsc/templates/dsc/deviceserver_advanced_search.html
{% extends request.is_ajax|yesno:"layout/ajax.html,dsc/layout/normal.html" %}
{% load staticfiles %}
{% load cms_tags i18n thumbnail webu_utils %}
{% load render_table from django_tables2 %}
{% load dsc_tags %}


{% block content_header %}
<h1 style="text-transform: none">Advanced Search</h1>
{% endblock %}
{% block content %}
        {% url 'deviceserver_add' as add_url %}



        <div>
            <h4>Please fill the search form:</h4>

        </div>
        <div>
            <form method="GET" class="get-form" >
                <table>
                    {{ form.as_table }}
                </table>
                <button type="submit" class="search btn btn-default">Search</button>
            </form>
        </div>
        {% if manufacturer or product or family or key_words or bus or dsc_user %}
        <div>
            <h4>Search results for:</h4>
            <ul>
                {% if manufacturer %}
                <li><span style="font-weight:bold;">Manufacturer:</span> {{manufacturer}}</li>
                {% endif %}
                {% if product %}
                <li><span style="font-weight:bold;">Product:</span> {{product}} </li>
                {% endif %}
                {% if bus %}
                <li><span style="font-weight:bold;">Bus:</span> {{bus}}</li>
                {% endif %}
                {% if family %}
                <li><span style="font-weight:bold;">Family:</span> {{family}} </li>
                {% endif %}
                {% if key_words %}
                <li><span style="font-weight:bold;">Key words:</span> {{key_words}}</li>
                {% endif %}
                {% if dsc_user %}
                <li><span style="font-weight:bold;">User:</span> {{dsc_user}}</li>
                {% endif %}

            </ul>
        </div>
        {% endif %}
        <span id="ds-table"></span>
        {% if table %}

            {% render_table table %}

             <div>
                <h4>Cannot find any device class you need?</h4>
                    Don't worry. Please ask on
                        <span style="font-weight:bold;font-size:120%;">
                            {{ 'info@tango-controls.org'|urlize|safe_for_robots }}</span>
                     mailing list. There could be some not yet added to the catalogue.
                </h4>

            </div>
        {% else %}
        <div style="text-align:center;font-weight:bold;">
            No search submitted, yet.
        </div>
        {% endif %}



{% endblock %}

{% block extra_script %}

    {{ block.super }}

    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

    {{ form.media }}


{% endblock %}

dsc/templates/dsc/deviceserver_class_select.html
{% extends request.is_ajax|yesno:"layout/ajax.html,dsc/layout/normal.html" %}
{% load cms_tags i18n thumbnail webu_utils %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

{% block content_header %}
<h1 style="text-transform: none">Deleting {{deviceserver.name}}</h1>
{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <h4>Are you sure you want to delete "{{ deviceserver.name }}" device class?</h4>
    <p>
    <button type="submit" value="Confirm" class="cancel btn btn-default">Delete</button>
    <a href="{% url 'deviceserver_detail' deviceserver.pk %}" class="dsc-back">Cancel</a>
    </p>
</form>


{% endblock %}

dsc/templates/dsc/deviceserver_detail.html
{% extends request.is_ajax|yesno:"layout/ajax.html,dsc/layout/dsc-detail.html" %}
{% load cms_tags i18n thumbnail webu_utils %}
{% load render_table from django_tables2 %}
{% load staticfiles %}
{% load markup_tags %}
{% load dsc_tags %}
{% load search_regx %}
{% load ratings %}
{% load comments %}


{% block extra_head %}
    {{ block.super }}
    <meta property="og:url" content="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}" />
	<meta property="og:type" content="article" />
	<meta property="og:title"  content="{{deviceserver.name}} Device Class/Server" />
    <meta property="og:description" content="{{og_description}}" />
    {% if deviceserver.picture %}
    <meta property="og:image" content="{{ deviceserver.picture.url }}" />
    {% else %}
    <meta property="og:image" content="{% static "dsc/img/default-ds-picture.png" %}" />
    {% endif %}

{% endblock %}

{% block meta_title %}
{{deviceserver.name}} - {{block.super}}
{% endblock %}


{% block content_header %}
<h1 style="text-transform: none">{{deviceserver.name}}</h1>
{% endblock %}

{% block content %}



{% if message %}
    <h4>{{message}}</h4>
{% endif %}

{% if deviceserver.is_valid %}
    <div id="fb-root"></div>

            <script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_EN/sdk.js#xfbml=1&version=v2.8";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
  <div style="margin-bottom:5pt">
      <span style="float:right;">
          <div class="fb-like" data-href="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
      </span>



        {% if user.is_authenticated %}
            <span style="margin-right:10pt;">
                <a href="{% url 'deviceserver_update' deviceserver.pk %}" class="icon-edit">Edit</a>
            </span>
        {% endif %}
        {% if deviceserver.created_by == user or perms.dsc.admin_deviceserver %}
            <span style="margin-right:10pt;">
                <a href="{% url 'deviceserver_delete' deviceserver.pk %}" class="icon-delete">Delete</a>

            </span>
        {% endif %}        .
    </div>
    <hr/>

{% endif %}

{% if deviceserver.certified %}
    <h4>This device server is certified as a reference implementation.</h4>
{% endif %}

{% if deviceserver.status == 'deleted' %}
    <h4>This device server is deleted.<br />Information provided here may be no longer valid.</h4>
{% endif %}
{% if deviceserver.status != 'deleted' and not deviceserver.is_valid %}
    <h4>This is historical information of device classes implemented in
        {{deviceserver.invalidate_activity.device_server.name}} device server.

    </h4>
        <a href="{% url 'deviceserver_detail' deviceserver.invalidate_activity.device_server.pk %}" style="font-weight:bold;">
            Use this link to find the valid information.
        </a>
{% endif %}

{% if deviceserver.is_valid %}
        <span style="float:right;margin-top:5pt; margin-bottom:5pt;margin-left:2em;">
            {% ratings deviceserver %}
        </span>
{% endif %}

<p style="margin-top:5pt; margin-bottom:5pt;">
    <span class="dsc-picture">
        {% if deviceserver.picture %}
        <img class="dsc-picture" src='{{ deviceserver.picture.url }}'>
        {% else %}
        <img class="dsc-picture" src='{% static "dsc/img/default-ds-picture.png" %}'>
        {% endif %}
    </span>

    <span style="font-weight:bold;">Development status:</span>
    {{ deviceserver.get_development_status_display }}{% if deviceserver.repository.tag %},
            <span style="font-weight:bold;">Release:</span> {{deviceserver.repository.tag}}
        {% endif %}
    <br />
    <span style="font-weight:bold;">Information status:</span> {{ deviceserver.get_status_display }}
    {% if deviceserver.status == 'new' or deviceserver.status == 'updated' %}
        {% if perms.dsc.admin_deviceserver %} <br />
            <span style="font-size:90%; margin-top:2pt;">As an administrator, you may
            <a href="{% url 'deviceserver_verify' deviceserver.pk %}"> <b>confirm</b></a>
            that information is valid.</span>
        {% endif %}
    {% endif %}


    <br />
    {% if deviceserver.repository.url or deviceserver.is_valid %}
    <span style="font-weight:bold;">Repository:</span>
    {% if deviceserver.repository.url %}
    <a href="{{deviceserver.repository.url}}" target="_blank">
        {{deviceserver.repository.url}}
    </a>

    {% else %}
    {% if deviceserver.device_classes.all.count > 1 %}
    These device classes are
    {% else %}
    This device class is
    {% endif %}

    not available in a public repository. Please contact the
    author{% if deviceserver.repository.contact_email %} {{ deviceserver.repository.contact_email|urlize }}{% endif %}.
    {% endif  %}
    {% if deviceserver.repository.download_url %}<br />
    <a href="{{deviceserver.repository.download_url}}" target="_blank">
        <span style="font-weight:bold;">Download</span>
    </a>
    {% endif %}
    {% endif %}
<br />
    <span style="font-weight:bold;">Contact:</span>
    {% for contact in contacts %}
        {{ contact|urlize|safe_for_robots }}

    {% endfor %}
</p>
{% if deviceserver.description %}
<h4>Description</h4>
<hr />
{% if deviceserver.description|find_match:'.*:.*:.*' %}
<p>{{ deviceserver.description|apply_markup:"restructuredtext" }}</p>
{% else %}
<p>{{ deviceserver.description|apply_markup:"markdown" }}</p>
{% endif %}
{% endif %}
<hr /> <br />


<div id="dsc-detail-tabs">
    <ul>
        {% for cl_name, spec in specifications.items %}
            {% if spec.cl.is_valid or not deviceserver.is_valid %}
            <li>
                <a href="#dsc-{{spec.cl.name}}-class-tab"><span>{{spec.cl.name}}</span></a>
            </li>
            {% endif %}
        {% endfor %}
        {% if deviceserver.is_valid %}
        <li style="float:right;">
            {% get_comment_count for deviceserver as comment_count %}
            <a href="#dsc-comments-tab"><span>Comments ({{comment_count}})</span></a>
        </li>
        {% endif %}
        <li style="float:right;">
            <a href="#dsc-documentation-tab"><span>Documentation</span></a>
        </li>
        <li style="float:right;">
            <a href="#dsc-history-tab"><span>History</span></a>
        </li>
    </ul>

    {% for cl_name, spec in specifications.items %}
        {% if True or spec.cl.is_valid or not deviceserver.is_valid %}
        <div id="dsc-{{spec.cl.name}}-class-tab">
            <h4>Class Description</h4>
            <hr />
            <p>
                {{ spec.cl.description|apply_markup:"restructuredtext"}}
            </p>
            <p>
                {% include 'dsc/inc/deviceserver_families.html' %}
            </p>

            <p><span style="font-weight:bold;">Key words:</span> {{spec.cl.info.key_words}}</p>
            {% if spec.cl.info.platform %}
                <p><span style="font-weight:bold;">Platform:</span> {{spec.cl.info.platform}}</p>
            {% endif %}

            {% if spec.cl.language %}
                <p><span style="font-weight:bold;">Language:</span> {{spec.cl.language}}</p>
            {% endif %}

            <p><span style="font-weight:bold;">License:</span>
                <a href="{{spec.cl.license.url}}" target="_blank">{{spec.cl.license.name}}</a>
            </p>
            <p><span style="font-weight:bold;">Contact:</span>
                {{ spec.cl.info.contact_email|urlize|safe_for_robots }}
            </p>
            {% if spec.cl.info.manufacturer or spec.cl.info.bus %}
                <h4>Hardware</h4>
                <hr />
                {% if spec.cl.info.manufacturer %}
                    <p><span style="font-weight:bold;">Manufacturer:</span> {{spec.cl.info.manufacturer}}
                    </p>
                    <p>
                        {% if spec.cl.info.product_reference %}
                            <span style="font-weight:bold;">Product:</span>
                            {{spec.cl.info.product_reference|apply_markup:"restructuredtext"}}
                        {% endif %}
                    </p>
                {% endif %}

                {% if spec.cl.info.bus %}
                    <p><span style="font-weight:bold;">Bus:</span> {{spec.cl.info.bus}}</p>
                {% endif %}

            {% endif %}


            <h4>Class interface</h4>
            <hr />
            <p>
                <span style="font-weight:bold;">Attributes:</span>
                {% render_table spec.attributes_table %}
            </p>
            <p>
                <span style="font-weight:bold;">Commands:</span>
                {% render_table spec.commands_table %}
            </p>
            <p>
                <span style="font-weight:bold;">Pipes:</span>
                {% render_table spec.pipes_table %}
            </p>
            <p>
                <span style="font-weight:bold;">Properties:</span>
                {% render_table spec.properties_table %}
            </p>

        </div>
        {% endif %}
    {% endfor %}
    {% if deviceserver.is_valid %}
    <div id="dsc-comments-tab">
        {% include 'dsc/inc/deviceserver_comments.html' %}
    </div>
    {% endif %}
    <div id="dsc-documentation-tab" style="word-break: break-all;">
        {% include 'dsc/inc/deviceserver_documentation.html' %}
    </div>

    <div id="dsc-history-tab">
        {% include 'dsc/inc/deviceserver_activities_list.html' %}

    </div>
</div>
<div>
    <span style="font-weight:bold;">Added by:</span>{{deviceserver.created_by}}
    <span style="font-weight:bold;">on:</span>{{deviceserver.created_at}}
</div>

{% endblock %}

{% block extra_script %}
    {{ block.super }}
    <script language="JavaScript">
        $("#dsc-detail-tabs").tabs();
    </script>

{% endblock %}